### ISSUE TITLE
EPIC: School and Term validations (B2: Backend Issue: schools controller: GET all, GET by id, POST)

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#19]
- [ ] POST /api/schools school (does backend validation of fields at least in terms of required/optional)
- [ ] GET /api/schools/all
- [ ] GET /api/schools?id=ucsb

**Comment by kjlee2504** [comment]
duplicate
