### ISSUE TITLE
EPIC: School and Term validation (F2: Frontend Create and Index Pages)

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#21]
**ALREADY COMPLETED by staff (F1: Frontend: Form)**
- [x]  Add "School" to the navbar
- [x]  Implement the Table for School (actual table, tests, storybooks)
- [x]  Index Page that uses table with link to delete and edit pages
- [x]  Create Page that uses form
- [x]  Edit page frontend.
