### ISSUE TITLE
EPIC: School and Term validations (F3: Frontend CourseForm uses schools dropdown)

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#22]
- [ ] Add separate component SchoolsDropdown that takes a list of schools as a prop (in the format returned by the backend GET /api/courses/all endpoint and provides a dropdown containing the abbrev values)
- [ ]  Add storybook and tests for SchoolsDropdown
- [ ]  Replace free form text for entering school with SchoolsDropdown
- [ ]  The default value of the SchoolsDropdown should be that no school is chosen, which should be a validation error for creating or updating a school (since school is required)
- [ ]  Make sure that all tests for create page and edit page still work.

**Comment by kjlee2504** [comment]
won't fix
