### ISSUE TITLE
EPIC: School and Term validations (F4: Frontend Course Form shows school specific term description)

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#23]
- [x] After selecting a school on the course form, the text for the termDescription for that school will be displayed near the place where the user is supposed to enter the term
- [x]  Any time the school is changed before the school is created or saved, the termDescription text should change
- [x]  That's all for this issue. Get this working first before tackling the regex thing

**Comment by kjlee2504** [comment]
Did not implement backend, pr closed by staff
