### ISSUE TITLE
EPIC: School and Term validations (F5: Frontend Course Form uses school specific regex.)

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#24]
- [x] After selecting a school on the course form, the regex for that school is loaded and applied to the value in the term field
- [x]  If the term field does not match the regex for that school, the school specific error message is displayed
- [x]  Any time the school is changed before the school is created or saved, the regex is reloaded and applied to the current value of term. If there is an error with the new regex, the new message is displayed.
- [x]  Any time the term field changes. the regex for the current school is applied to the new contents, and the error message updates if needed.
- [x]  When the school is entered, a term is entered, and the matching regex is satisfied, no error message displays and the user is permitted to save the new or updated school.

**Comment by kjlee2504** [comment]
did not implement backend, pr closed by staff
