### ISSUE TITLE
EPIC: CRUD operations for Courses, Course Staff (B1: Backend POST / GET operations, Course Controller (partially complete))

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#25]
- [ ] There is a POST endpoint /api/course/create where you can create a course. When a users creates a course, the users that creates the course should be added to the CourseStaff table.
- [ ]  There is a GET endpoint /api/course/getAll that gets all courses if you are an admin. Otherwise, as long as you are logged in, you get all the courses for which you are on the course staff.
- [ ]  There is a GET endpoint /api/course/get?id=123 that gets the course with id 123 if you are an admin, or if you are logged in and on the course staff.

**Comment by kjlee2504** [comment]
Duplicate
