### ISSUE TITLE
EPIC: CRUD operations for Courses, Course Staff (F5: Course staff frontend (POST to add new staff))

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#28]
- [ ] There is an AddCourseStaffForm that has a single field: one where you enter the github id of a new staff member, along with tests and a storybook entry. The field must be nonblank.
- [ ]  The course staff page has a button: add staff member that takes you to a page at a frontend url called /courses/{courseId}/staff/create
- [ ]  The create pages takes in the github id, and passes it to the backend. On success, the user is routed back to the index page for the course staff for that course. On failure, an error message is shown.

**Comment by kjlee2504** [comment]
won't fix
