### ISSUE TITLE
EPIC: CRUD operations for Courses, Course Staff (F4: Course staff frontend (GET, DELETE index page))

### ISSUE THREAD

**Issue by kjlee2504** [ucsb-cs156-w24/proj-organic-w24-6pm-2#29]
- [ ] There is a button on the course table labelled "Staff" that navigates to the staff page at the frontend url /courses/{courseId}/staff. This page can initially be a placeholder if you want to separate this item into its own issue.
- [ ] There is a table component to list staff members, and fixures that match the GET /api/course/staff/all?courseId=123 endpoint
- [ ] The page /courses/{courseId}/staff retrieves the data from the backend and shows the staff for that course.
- [ ] The staff table has a delete button that invokes the DELETE endpoint for that staff member.

**Comment by kjlee2504** [comment]
won't fix
