### ISSUE TITLE
EPIC: School and Term validations (B2 + B3)

### ISSUE THREAD

**Issue by mbharti12** [ucsb-cs156-w24/proj-organic-w24-6pm-2#45]
**B2:**
- [ ] POST /api/schools school (does backend validation of fields at least in terms of required/optional)
- [ ] GET /api/schools/all
- [ ] GET /api/schools?id=ucsb

**B3:**
- [ ] PUT /api/schools?id=123
- [ ] DELETE /api/schools?id=123

**Comment by kjlee2504** [comment]
won't fix
